### PR TITLE
Check login status with Ajax before refreshing page.

### PR DESCRIPTION
**Pull request by marcus-downing**
## Because

The current experience is unfriendly if somebody times out while they have unsaved content:

1. It shows a 10-second warning. Let's assume somebody misses that.
2. It shows a "You have been logged out" popup over the page.
3. It shows a login box popup over that.
4. On returning to the page, the user logs in with the login box.
5. The other popup is still there. They click "OK" to dismiss.
6. It tries to refresh the page. This prompts a browser message saying, "Are you sure you want to navigate away? Unsaved changes will be lost."

In reality, WordPress has saved the changes in an autosave, which can be recovered with one click. But a nervous user may not know or appreciate that when told they're going to lose work.

## This change

Adds an Ajax endpoint to check whether there is a user logged in right now.

On clicking "OK" to dismiss, it uses Ajax to check whether the user is now logged in. If they are, the box goes away. If not, it refreshes as before.

### CODE REVIEW

**Comment by techies23** [comment]
Hi Marcus,

Sorry for the trouble but i just pulled in and updated the plugin just now so can you please pull this new source and make changes there and send in PR ? 

Thanks

**Comment by marcus-downing** [comment]
Okay, I've merged, fixed and rebased to your latest `master`.

**Comment by marcus-downing** [comment]
Is there anything I can do to help get this merged?

**Comment by techies23** [comment]
Haven' t had time to look at it yet.. I'll keep posted

**Comment by techies23** [comment]
I pulled the code into my local and did a check and it works only on first level.  After default WP login popup appears and user logs in and edits again however, the problem appears when user is still on the  same page the popup never appears again unless the page is refreshed again.

Why this happens ? This happens because the logged out nonce and logged in nonce does not match because of which popup or next logout never happens unless browsed to next page or refreshed which would only work for one level.

Do suggest if you have a solution to this. I tried debugging this issue but could not fix this issue on my side. Thnx

**Comment by marcus-downing** [comment]
I've updated the MR to get a new security nonce when the "is_user_logged_in" action says "yes". However, the behaviour still isn't correct on subsequent logouts.

**Comment by marcus-downing** [comment]
I think the answer to better behaviour here is to fit closer within the WordPress Heartbeat API.

At regular intervals (generally every 15-60 seconds), WordPress calls an Ajax action, and plugins can piggyback on this to pass data to a PHP action, and pass data back. This lazy Ajax seems perfectly in keeping with the way this _Inactive Logout_ plugin works, and proper use of the Heartbeat API could replace all the custom Ajax actions.

Notably, one of the pieces of information the heartbeat returns with each tick is whether or not the user is logged in.

```json
{
    "wp-auth-check": false,
    "server_time": 1516974513
}
```

**Pull request closed without merging**
